"""Add price_per_unit to Schedule

Revision ID: b0c8818ad67d
Revises: 017c9f8ddb3c
Create Date: 2024-08-06 11:19:37.292157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c8818ad67d'
down_revision = '017c9f8ddb3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_unit', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_column('price_per_unit')

    # ### end Alembic commands ###
